### PR TITLE
Use go-modules

### LINKED ISSUE #7: Switch to go modules.

### PR DESCRIPTION
**Pull request by epk**
Closes #7

### CODE REVIEW

**Comment by ekhabarov** [comment]
Hi @epk! Thank you for the PR. 

Everything work fine except `make generate` command, which updates example project in `example` directory and imports `gogo.proto` file from `vendor` directory.

See [Makefile](https://github.com/bold-commerce/protoc-gen-struct-transformer/blob/master/Makefile#L9) and [example/message.proto](https://github.com/bold-commerce/protoc-gen-struct-transformer/blob/master/example/message.proto#L10) for details.

With Go modules it could be used as 

```diff
diff --git a/Makefile b/Makefile
index d5cf219..7ce93e4 100644
--- a/Makefile
+++ b/Makefile
@@ -6,7 +6,7 @@ LDFLAGS= -ldflags '-X github.com/bold-commerce/protoc-gen-struct-transformer/gen

 re-generate-example:
        protoc \
-               --proto_path=vendor/github.com/gogo:. \
+               --proto_path=$(GOPATH)/pkg/mod/github.com/gogo:. \
                --struct-transformer_out=package=transform,debug=false,helper-package=helpers:. \
                --gogofaster_out=Moptions/annotations.proto=github.com/bold-commerce/protoc-gen-struct-transformer/options:. \
                ./example/message.proto
diff --git a/example/message.proto b/example/message.proto
index fb184a0..62872e0 100644
--- a/example/message.proto
+++ b/example/message.proto
@@ -7,7 +7,7 @@ option (transformer.go_models_file_path) = "example/model/model.go";
 option go_package = "example"; // Package name for pb.go

 import "options/annotations.proto";
-import "protobuf/gogoproto/gogo.proto"; // for gogoproto options
+import "protobuf@v1.3.0/gogoproto/gogo.proto"; // for gogoproto options
 import "google/protobuf/timestamp.proto";

 message TheOne{
```

* Can we relay on Go modules cache which is located in `$(GOPATH)/pkg/mod` for importing `*.proto` files? Or maybe there is better solution?
* How we can fix version for specific modules? `github.com/gogo/protobuf` in this case.

Thanks!

**Comment by ekhabarov** [comment]
Hi @epk, could you please, take a look at comment above? ^

**Comment by epk** [comment]
> Hi @epk, could you please, take a look at comment above? ^

Hi Evgeny, sorry for the delayed response,I am in a middle of a move currently, I will take a look into this on Sunday

**Comment by ekhabarov** [comment]
@epk, great, thank you!

**Review by ekhabarov — APPROVED** [review]

**Pull request merged**
